steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/aibot', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/aibot' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - aibot
      - --image=gcr.io/$PROJECT_ID/aibot
      - --region=asia-southeast1
      - --platform=managed

options:
  logging: CLOUD_LOGGING_ONLY
